SongRecomendationSite/Models/FormData.cs
namespace SongRecommendationSite.Models
{
    public class FormData
    {
        public string Artist { get; set; }
        public string Title { get; set; }
        public string Mood { get; set; }
        public string Style { get; set; }
    }
}

SongRecomendationSite/Models/ViewModels/HomeViewModel.cs
using System.Web.Mvc;

namespace SongRecommendationSite.Models.ViewModels
{
    public class HomeViewModel
    {
        public SelectList Styles { get; set; }
        public string CurrentStyle { get; set; }
        public SelectList Moods { get; set; }
        public string CurrentMood { get; set; }
        public FormData Data { get; set; }
    }
}

SongRecomendationSite/Models/ViewModels/RecommendationViewModel.cs
namespace SongRecommendationSite.Models.ViewModels
{
    public class RecommendationViewModel
    {
        public string Artist { get; set; }
        public string Title { get; set; }
    }
}

SongRecomendationSite/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SongRecommendationSite.Helpers;
using SongRecommendationSite.Models.ViewModels;

namespace SongRecommendationSite.Controllers
{
    public class HomeController : Controller
    {
        private const string MOOD = "mood";
        private const string STYLE = "style";

        public ActionResult Index()
        {
            var moods = APIHelper.GetTermsFromAPI(MOOD);
            var styles = APIHelper.GetTermsFromAPI(STYLE);
            var model = new HomeViewModel
            {
                Moods = GetListOfItems(moods),
                Styles = GetListOfItems(styles)
            };
            return View(model);
        }

        private static SelectList GetListOfItems(IReadOnlyCollection<string> list)
        {
            var result = new List<SelectListItem> { new SelectListItem
                        {
                            Value = string.Empty,
                            Text = string.Empty
                        }};
            if (list.Any())
                result.AddRange(GetItemsFromList(list));
            return new SelectList(result, "Value", "Text");
        }

        private static IEnumerable<SelectListItem> GetItemsFromList(IEnumerable<string> list)
        {
            return list
                .Select(x =>
                    new SelectListItem
                    {
                        Value = x,
                        Text = x
                    });
        }
    }
}

SongRecomendationSite/Controllers/RecommendationController.cs
using System.Linq;
using System.Web.Mvc;
using System.Xml.Linq;
using SongRecommendationSite.Helpers;
using SongRecommendationSite.Models;
using SongRecommendationSite.Models.ViewModels;

namespace SongRecommendationSite.Controllers
{
    public class RecommendationController : Controller
    {
        [HttpPost]
        public ActionResult GetRecommendation(FormData data)
        {
            var recommendation = APIHelper.GetRecommendationFromAPI(data);
            if (RecommendationNotValid(recommendation))
                return View(new RecommendationViewModel()); ;
            var model = new RecommendationViewModel
            {
                Artist = recommendation.Descendants("artist_name").FirstOrDefault().Value,
                Title = recommendation.Descendants("title").FirstOrDefault().Value
            };
            return View(model);
        }

        private static bool RecommendationNotValid(XContainer recommendation)
        {
            return recommendation == null || recommendation.Descendants().All(e => e.Name != "artist_name")
                   || recommendation.Descendants().All(e => e.Name != "title");
        }
    }
}

SongRecomendationSite/Views/Home/Index.cshtml
@model SongRecommendationSite.Models.ViewModels.HomeViewModel

@{
    ViewBag.Title = "Song Recommender";
}

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<div class="jumbotron">
    <h1>Song Recommender</h1>
    <p class="lead">A simple song recommendation tool, recommending songs based on your preferences.</p>
</div>

<div class="col-lg-12">
    <div class="col-md-6">
        <h2>Song preferences</h2>
        <p>Here are some questions to help find you the perfect song.</p>
        @using (Ajax.BeginForm("GetRecommendation", "Recommendation", null, new AjaxOptions
        {
            HttpMethod = "POST",
            UpdateTargetId = "recommendation"
        }, new { id = "Prefrences" }))
        {
            @Html.AntiForgeryToken()
            @Html.LabelFor(x => x.Data.Artist, "Band: ")
            <br />
            @Html.EditorFor(x => x.Data.Artist, new { style = "width:250px;" })<br />
            @Html.LabelFor(x => x.Data.Title, "Song: ")<br />
            @Html.EditorFor(x => x.Data.Title, new { style = "width:250px;" })<br />
            @Html.LabelFor(x => x.Data.Style, "Style: ")<br />
            @Html.DropDownListFor(x => x.Data.Style, Model.Styles, new { style = "width:250px;" })<br />
            @Html.LabelFor(x => x.Data.Mood, "Mood: ")<br />
            @Html.DropDownListFor(x => x.Data.Mood, Model.Moods, new { style = "width:250px;" })<br /><br />
            <input type="submit" class="btn btn-default" value="Find my song" />
        }
    </div>
    <div class="col-md-6" id="recommendation">
        <h2>How to use</h2>
        <p>To use the recommendation service please fill out your desired song specifications in the preferences form.</p>
        <p>You can either serach by entering a band or/and a song title, or you can serach by selecting a style and/or mode.</p>
        <p>When your ready just hit the submit button and let us do the heavy lifting.</p>
    </div>
</div>

SongRecomendationSite/Views/Recommendation/GetRecommendation.cshtml
@{
    @model SongRecommendationSite.Models.ViewModels.RecommendationViewModel
    Layout = "";
}
<div id="recommendation" class="col-md-6">
    @if (!string.IsNullOrWhiteSpace(Model.Artist) && !string.IsNullOrWhiteSpace(Model.Title))
    {
        <h2>This is your recommendation</h2>
            <p>
                <b>Artist:</b> @Model.Artist
                <br />
                <b>Title:</b> @Model.Title
            </p>
    }
    else
    {
        <h2>Could not find a recommendation</h2>
        <p>
            For some reason we where not able to find you a recommendation. Try changing you preferences and then try again.
        </p>
    }
</div>

SongRecomendationSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
</div>
    <div class="col-md-12">
    <hr />
<p align="center">&copy; @DateTime.Now.Year - Song Recomendations INC.</p>
</div>
</body>
</html>